---
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'vllm'
        scrape_interval: 5s
        static_configs:
          - targets: ['0.0.0.0:8000']

  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    send_batch_size: 100
    timeout: 1s
  resourcedetection/system:
    detectors: ["system"]

  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25

exporters:
  #otlphttp/dynatrace:
  #  endpoint: "https://ENVIRONMENT.live.dynatrace.com/api/v2/otlp"
  #  headers:
  #    Authorization: "Api-Token xxxx.XXXX.XXXXXX"
  #otlphttp/ocp:
  #  endpoint: https://otlp-http-otlp-receiver-route-observability.apps.ocp-beta-test.nerc.mghpcc.org
  #  tls:
  #    insecure: false
  #    cert_file: /certs/server.crt
  #    key_file: /certs/server.key
  #    ca_file: /certs/ca.crt

  prometheus:
    endpoint: 0.0.0.0:8888 #<-with this you can `curl localhost:8888/metrics` to see all metrics

  debug:
    verbosity: basic  #<-switch to 'detailed' to see metrics in otel-collector logs

service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, memory_limiter]
      exporters: [prometheus, debug]
